name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
            npm install --global --production windows-build-tools --vs2015
            npm config set msvs_version 2015 –global
            npm config set python python2.7

      - name: Install yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn

      - name: Build react app
        run: yarn run build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
